# Generated by Django 3.2.8 on 2021-10-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='SubFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=18)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preciodescuento', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_categoria', to='articulos.categoria')),
                ('familia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_familia', to='articulos.familia')),
                ('marca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='marca', to='articulos.marca')),
                ('subcategoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_subcategoria', to='articulos.subcategoria')),
                ('subfamilia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subfamilia', to='articulos.subfamilia')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=5)),
                ('inventario', models.IntegerField(default=0)),
                ('upc', models.CharField(max_length=15, unique=True)),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
            ],
            options={
                'unique_together': {('padre', 'talla')},
            },
        ),
    ]
